name: lifetimevalue
version: 0.4.0
author: Filip Hracek <filiph@google.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
  test: any
