name: lifetimevalue
version: 0.3.0
author: Filip Hracek <filiph@google.com>

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  browser: '>=0.10.0+2 <0.11.0'

dev_dependencies:
  dart_to_js_script_rewriter: any
  test: any

transformers:
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter
